### ISSUE TITLE
CH376 with SPI

### ISSUE THREAD

**Issue by AbdelazezMRX** [djuseeq/Ch376msc#31]
i am using Arduino Mega With CH376 using SPI, but when i see the data frame using logic analiser it seems that i have no response,
just the same data i sent using SPI is return back again, i don't know if the problem in the connection or what , but i tried many configurations to the pins and still not working , and i need it because it is part from my graduation project.
i hope to help me fixing the problem, and thanks
![114](https://user-images.githubusercontent.com/65266562/89478472-5df7ba00-d790-11ea-8eba-eb48f3761f49.PNG)

**Comment by djuseeq** [comment]
Hi, so there is no response at all from the module? While sending data to the module, is it normal if you get back the previously sent byte from modules shiftregister , the arduino will discard it, so when arduino wants to read data from the module , it would send 0x00 to the module while in the same time receives the useful data from the module.

**Comment by AbdelazezMRX** [comment]
thanks for your reply,
but when i send 0x00 to module to get the useful data i just get the previous byte i had send, i mean the module doesn't respond with any data, it is just work as a shift register, i don't know if the problem in the connection or what, because the datasheet says to make TX/RX HIGH when using SPI and make A0 also HIGH, and this is different from the picture in your library.

**Comment by djuseeq** [comment]
Ok, if you use this library then you don`t need to send any data directly to the module, the lib will do that. You have to check the connection between the module and the Arduino board and jumper config. If your module differs from my one, then its better to inspect with DMM or just check the printed text on the module and pull to ground RD and WR pins and pull it to HIGH(probably 3.3V) the PCS pin. Check the TXD pin, if its pulled to the ground with jumper then remove that jumper (serial mode).
![Screenshot_20200806_234435](https://user-images.githubusercontent.com/30174351/89586704-7d4e2000-d840-11ea-9d36-9ceee4eb01dc.png)
