### ISSUE TITLE
Donate Link (:

### ISSUE THREAD

**Issue by petervanderwalt** [djuseeq/Ch376msc#42]
Do you have any way for us to buy you a coffee, or contribute towards your work? As a token of appreciation for this awesome library (:

**Comment by djuseeq** [comment]
Thank you very much, your intention and appreciation is a very good feeling for me. I'm glad you like it and find it useful. I only have a PayPal account. I don't know how appropriate PayPal for this purpose. [Coffee (:](https://paypal.me/djusee)

**Comment by petervanderwalt** [comment]
Thanks, will bring it up at the next company meeting (:
