### ISSUE TITLE
File not created on my pendrive but read works on serial monitor

### ISSUE THREAD

**Issue by Aravinthkalai1** [djuseeq/Ch376msc#45]
It's working fine on serial monitor ever functions works fine but when I eject Pendrive and insert it into my pc there are no files created! am using windows 10 64bit please help me to sort out the issue.

**Comment by djuseeq** [comment]
Hi. Yes, that is a [known problem](https://github.com/djuseeq/Ch376msc#known-issues) with modules which have a chip with obsolete firmware. Please check your chip's firmware version, calling getChipVer() function and print it on serial terminal. Please read the possible solution [here](https://github.com/djuseeq/Ch376msc#firmware-difference) .

**Comment by Aravinthkalai1** [comment]
It's working fine. I just formatted my Pendrive with Active@ Partition Manager, thank you for your guidance.
