### ISSUE TITLE
readFileUntil() return "false" for both EOF and the record terminator

### ISSUE THREAD

**Issue by gpb01** [djuseeq/Ch376msc#66]
The method **readFileUntil()** return "false" for both EOF and the record terminator (_terminate character_) making it impossible to read record by record a file since, as soon as the terminator of a record (_terminate character_) is encountered, "**false**" is returned and it is no longer known whether there are further records or not.

The problem is in this "if":

```
if( (tmpBuff[0] == trmChar ) || !readMore ){ // reach terminate character or EOF
   readMore = false;
   break;
}
```

which I suggest to modify as follows:

```
if( !readMore ) { // reach EOF
   readMore = false;
   break;
}
if( tmpBuff[0] == trmChar ){ // reach terminate character
   break;
}
```

to return "false" only in case of EOF.

Guglielmo

**Comment by gpb01** [comment]
Ok, in your library examples I have seen that you use another method to recognize the EOF (_getEOF()_) and you use the boolean returned by the method readFileUntil() both to indicate if the terminator has been found or not and for the EOF.

Even if I prefer what I have explained on the previous post, I respect your choice, so ... the issue can be closed.

Guglielmo

**Comment by djuseeq** [comment]
Hi thanks for suggestion and sorry for late reply. Yes, your way is simpler but i used this way if the buffer is not large enough and becomes full but the newline char is not reached yet then in that case i can detect and handle it.

**Comment by gpb01** [comment]
Hi,
thanks for your answer. Yes, of course, possible with malformed records so ... good idea. :-)

Guglielmo
