### ISSUE TITLE
Possible to open other file types ?

### ISSUE THREAD

**Issue by gcharles81** [djuseeq/Ch376msc#9]
Hello thanks for this library 
Is it possible to open other file types ? or it will support only TXT files
thanks

**Comment by djuseeq** [comment]
Hi, it's my pleasure . Actually yes, you can open , but probably it gonna be unusable. The CH chip will send a large pile of bytes and that somehow needs to be processed. If the goal is some data logging then best choice is CSV(Comma-separated values), it's easy to open in MS excel or LibreOffice. Which extension are you interested in? Here's an example to see what I'm talking about. 
![Screenshot_20191001_004607](https://user-images.githubusercontent.com/30174351/65923628-e0ce1c80-e3e9-11e9-8542-06d45d2f3fdd.png)
![Screenshot_20191001_005531](https://user-images.githubusercontent.com/30174351/65923672-09561680-e3ea-11e9-8343-4caffae267da.png)

**Comment by luc-github** [comment]
hi sorry to jump in conversation but as topic is still open ;)
I did not dig in code yet but do you mean that reading binary like pictures may be a problem?
I would like to store text based files as well as binaries for images

**Comment by djuseeq** [comment]
Hi, i haven't tried  to use for binary files. But that feature can be useful , i will experiment with it

**Comment by djuseeq** [comment]
Hi @luc-github , maybe [this](https://github.com/djuseeq/Ch376msc/issues/35#issuecomment-717952129) can be useful for You.

**Comment by luc-github** [comment]
@djuseeq thank you - I am super late to integrate your lib - I will check that when on it
